### ISSUE TITLE
MeshSync breaks on Blender 2.79 daily build

### ISSUE THREAD

**Issue by bitinn** [unity3d-jp/MeshSync#24]
I just realize this:

With [2.79b stable release](https://www.blender.org/download/) (2018 March), everything is fine.

With [2.79 daily build](https://builder.blender.org/download/) (2018 August, based on their master branch), it is showing this error:

<img width="761" alt="screen shot 2018-08-28 at 14 25 26" src="https://user-images.githubusercontent.com/1484279/44706613-c33acf00-aad4-11e8-83c3-8950fcd0bfbe.png">

I am reverting back to 2.79b, so this is not an immediate issue for me. If Blender releases 2.79c at some point, then MeshSync might break.

So a heads-up for other users.

**Comment by i-saint** [comment]
thanks for the info. but it is a known issue.
MeshSync directly accesses Blender's internal data structure (because python is far too slow). that means if Blender's data structure changed, it no longer works and we need to recompile it with corresponding header files in Blender's source code.
we won't support daily build because it requires too many efforts.
