### ISSUE TITLE
Doesn't sync material changes in blender

### ISSUE THREAD

**Issue by wewrere41** [unity3d-jp/MeshSync#743]
Non URP
Its doesnt change color of material in unity when I change the color on blender. And  materials looks purple, Its creating material with wrong shader I think. I have to change material shader to default. Then I have to export mesh and import mesh again in blender. And its gets materials correctly on unity. 
URP 
Its doesnt change color of material in unity when I change the color on blender.  Even if I export mesh and import mesh again in blender,  it doesnt get color. Because MeshSync using "_Color" property for color and URP shader using "_BaseColor" for color.

**Comment by sindharta** [comment]
Both syncing materials and syncing the "base" color of materials are currently not supported yet in Blender.

What you can do to convert manually by creating materials in Unity and assigning these Unity materials into the material list in [the MeshSyncServer inspector](https://docs.unity3d.com/Packages/com.unity.meshsync@0.13/manual/CommonMeshSyncProperties.html#material-list).
Then, MeshSync will maintain this "conversion".

That being said, we should not see purple color anytime in Unity.
Can you please share a video / screenshot/ asset so that we can reproduce this issue ?

**Comment by wewrere41** [comment]
Standart/Non URP

Purple fixed in new project.
Its doesnt get color. I have to import/export mesh. And gets correct color. I have to export/import every time when I change color on blender. Or I have to pause sync and resume sync. Then gets color.

https://user-images.githubusercontent.com/45511976/182394903-d09d0fd6-3eea-4afc-9da4-d5c064a46399.mp4

URP
Even if I export and import mesh again in blender, it doesnt get color because MeshSync editing wrong color property. MeshSync changing "_Color" property for color but URP shader using "_BaseColor" property for color.



https://user-images.githubusercontent.com/45511976/182397801-fa538b25-28f8-420c-aad9-d740d8d6b499.mp4

**Comment by sindharta** [comment]
> Purple fixed in new project.

Ok, so there is no problem indicated by purple objects, isn't it ?
Thank you for the confirmation.

**Comment by wewrere41** [comment]
> 

Yes purple fixed but there are another problems with the materials as I showed in the video

**Comment by sindharta** [comment]
> there are another problems with the materials

Yes, like I mentioned, both syncing materials and syncing the "base" color of materials are currently not supported yet in Blender. We are putting these in our backlog.

**Comment by wewrere41** [comment]
> > there are another problems with the materials
> 
> Yes, like I mentioned, both syncing materials and syncing the "base" color of materials are currently not supported yet in Blender. We are putting these in our backlog.

Okay, good work.
