### ISSUE TITLE
Geometry nodes not synced when RealizeInstances node is used

### ISSUE THREAD

**Issue by Wozniax1** [unity3d-jp/MeshSync#776]
I attached a blend file with a geometry node setup that is not showing in Unity when sync is enabled.
[GN_Curve_Array.zip](https://github.com/unity3d-jp/MeshSync/files/9590467/GN_Curve_Array.zip)

Another sync issue I noticed is when I used Delete Geometry node to remove a face from a cube it works in blender but in Unity unchanged cube is synced. It is synced correctly only when geometry node modifier is applied.

**Comment by schinkowski** [comment]
Thanks for your feedback @Wozniax1.

If you enable the option to "bake modifiers" in MeshSync and go into Object mode in blender, the mesh should be synced correctly. We do not currently support applying modifiers like geometry nodes in edit mode.

For the "delete geometry" node to work you also need to enable the "bake modifiers" option and it should work.

**Comment by Wozniax1** [comment]
Hi, thanks for clarification. 

Bake modifiers option applies the modifiers, so it is not using geometry nodes anymore, and I cannot have separate instances. 
I have whole model as one mesh instead.

**Comment by schinkowski** [comment]
I think the problem comes from the realize instances node. That node turns the instances into actual geometry and joins them to a single mesh. You would need to find a way to make it work without that node so they remain instances. I'm not sure how you could achieve the same result with that though because you are deforming the instances along the curve so each instance needs to be different.

**Comment by Wozniax1** [comment]
Thanks for explanation

**Comment by sindharta** [comment]
Closing. 
Feel free to reopen if there are any more related questions.
